### PR TITLE
PEOPLE: Data quality on `Person#show`

### LINKED ISSUE #797: PEOPLE: Datenqualitäts-Issues auf Person anzeigen
Als User mit Schreibrechten möchte ich bei einer Person sehen, ob Probleme mit der Datenqualität vorliegen.

Neu soll auf der Person Show Seite zuoberst in der rechten Spalte ein Abschnitt "Datenqualität" angezeigt werden, falls der User Schreibrechte auf der angezeigten Person hat und `Person#data_quality != :ok` ist.

Alle Einträge der Person in `Person::DataQualityIssue` werden, nach `severity` geordnet (höchste zuoberst), als Liste dargestellt. Es sollen keine Bullet Points angezeigt werden.

Jeder Eintrag hat zuerst ein Icon gemäss der `severity`, mit entsprechendem Tooltip:

- error: [times-circle](https://fontawesome.com/v5/icons/times-circle?s=solid), "Fehler"
- warning: [exclamation-triangle](https://fontawesome.com/v5/icons/exclamation-triangle?f=classic&s=solid), "Warnung"
- info: [info-circle](https://fontawesome.com/v5/icons/info-circle?f=classic&s=solid), "Info"

Danach folgt die zugehörige Meldung (`message`).

# ToDo

- [x] View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

### PR DESCRIPTION
**Pull request by hunchr**
Fixes #797

image

### CODE REVIEW

File: app/helpers/sac_cas/people_helper.rb [hunk 1]
```diff
@@ -36,6 +36,16 @@ def people_sac_membership_qr_code(person, html_options = {})
...
   end
 
+  def format_data_quality_icons(status)
+    icons = {
+      ok: "check-circle",
+      info: "info-circle",
+      warning: "exclamation-triangle",
+      error: "times-circle"
+    }
+    icon(icons[status.to_sym], title: I18n.t("people.data_quality.#{status}"))
```
Comment (njaeggi) [inline app/helpers/sac_cas/people_helper.rb:46]:
```
icon_name = icons[status.to_sym]
icon(icon_name, title: I18n.t("people.data_quality.#{status}"))
```

File: app/views/people/_attrs.html.haml [hunk 2]
```diff
@@ -0,0 +1,46 @@
+-#  Copyright (c) 2024, Schweizer Alpen-Club. This file is part of
```
Comment (njaeggi) [inline app/views/people/_attrs.html.haml:1]: When a view partial should be extended inside a wagon, we don't copy the core partial and adjust some small stuff

In general the way to go here is to define a new partial in the wagon and then use `render_extensions` to add the part we want to add

A good example is `_details_sac_cas.html.haml` or `_fields_sac_cas.html.haml`

since you already have `_data_quality_sac_cas.html.haml`, you should be able to call

`render_extensions: :data_quality`

in the core partial and removing this copied file

**Review by njaeggi — CHANGES_REQUESTED** [review]
Only small issue with how we adjust views in wagons, the rest looks good :rocket:

File: app/views/people/_attrs.html.haml (hunk 2 above)
Comment (hunchr) [reply app/views/people/_attrs.html.haml]: wow, that's clever
https://github.com/hitobito/hitobito/pull/2781

**Review by njaeggi — APPROVED** [review]
